# Generated by Django 3.1.7 on 2021-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210319_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_data',
            name='reliever_duty',
            field=models.BooleanField(default=False),
        ),
    ]
