# Generated by Django 3.1.7 on 2021-03-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210319_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_data',
            name='exam_timetable_csv_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
