# Generated by Django 3.1.7 on 2021-03-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210319_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_data',
            name='exam_timetable_csv_location',
        ),
        migrations.RemoveField(
            model_name='exam_data',
            name='name_of_departments',
        ),
        migrations.AddField(
            model_name='deprtment_data',
            name='exam_timetable_csv_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deprtment_data',
            name='name_of_departments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='exam_data',
            name='reliever_duty',
            field=models.IntegerField(),
        ),
    ]
