# Generated by Django 3.1.7 on 2021-04-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210325_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deprtment_data',
            name='proofORlecture_csv_location',
        ),
    ]
