# Generated by Django 3.1.7 on 2021-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_deprtment_data_prooforlecture_csv_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_data',
            name='InterorIntra',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
