# Generated by Django 3.1.7 on 2021-05-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_exam_data_interorintra'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_notif',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_save',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('fac_dept', models.CharField(max_length=150)),
                ('dept', models.CharField(max_length=150)),
                ('slot', models.CharField(max_length=150)),
                ('categ', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.exam')),
            ],
        ),
    ]
