# Generated by Django 3.1.7 on 2021-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deprtment_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_csv_location', models.CharField(blank=True, max_length=150, null=True)),
                ('availability_csv_location', models.CharField(blank=True, max_length=150, null=True)),
                ('proofORlecture_csv_location', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name_of_exam', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description_of_exam', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_blocks', models.IntegerField()),
                ('tot_departments', models.IntegerField()),
                ('name_of_departments', models.CharField(max_length=150)),
                ('reliever_duty', models.BooleanField(default=True)),
                ('extra_blocks', models.IntegerField()),
                ('exam_timetable_csv_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='CSV',
        ),
    ]
