# Generated by Django 3.1.7 on 2021-03-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210320_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deprtment_data',
            old_name='name_of_departments',
            new_name='name_of_department',
        ),
    ]
