# Generated by Django 3.1.7 on 2021-03-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210320_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
