# Generated by Django 3.1.7 on 2021-03-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210320_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_data',
            name='exam_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accounts.exam'),
            preserve_default=False,
        ),
    ]
