# Generated by Django 3.1.7 on 2021-03-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_exam_data_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deprtment_data',
            name='exam_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='description_of_exam',
            field=models.TextField(blank=True, null=True),
        ),
    ]
