# Generated by Django 3.1.7 on 2021-05-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210501_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_data',
            name='extra_blocks',
        ),
        migrations.RemoveField(
            model_name='exam_data',
            name='tot_blocks',
        ),
    ]
