# Generated by Django 3.1.7 on 2021-05-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210502_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duty',
            new_name='SDuty',
        ),
    ]
