# Generated by Django 3.1.7 on 2021-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210503_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sduty',
            name='date',
            field=models.CharField(max_length=150),
        ),
    ]
