# Generated by Django 3.1.7 on 2021-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210503_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='sduty',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
